FROM golang:1.24 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o client cmd/client/main.go

FROM scratch
WORKDIR /app
COPY --from=builder /app/client .
EXPOSE 8080
ENTRYPOINT ["./client"]
